### ISSUE TITLE
Update related pages and links

### ISSUE THREAD

**Issue by slel** [mkauers/ore_algebra#10]
Can someone check the `ore_algebra` version information and links
are accurate on the following few webpages, and if not, fix them or
try to get them fixed?

- http://fredrikj.net/
- http://www.kauers.de/software.html
- https://github.com/mkauers/ore_algebra/
- http://www.algebra.uni-linz.ac.at/people/mkauers/ore_algebra/
- https://www3.risc.jku.at/research/combinat/software/ore_algebra/
- https://www3.risc.jku.at/research/combinat/software/ore_algebra/doc/

Having version information in many places requires updating it in
many places... and increases chances some places will have out
of date information. Most pages might avoid getting out of date
by stating the latest version can be found on the "releases" page:

- https://github.com/mkauers/ore_algebra/releases

**Comment by mkauers** [comment]
Thanks for pointing out this issue. 
Links on fredrikj.net and kauers.de and github seem ok. 
The pages at algebra.uni-linz.ac.at are docstrings of a particular release. 
The pages at risc.jku.at are really outdated, but I no longer have access to them. I will see if I can get them to include a link to github.
