### ISSUE TITLE
Result of guess does not live in specified algebra

### ISSUE THREAD

**Issue by smelczer** [mkauers/ore_algebra#15]
The result of guessing a differential equation over a differential algebra with rational coefficients is an element of a differential algebra with integer coefficients. For instance,

```
from ore_algebra import *
Pols.<x> = PolynomialRing(QQ); Diff.<Dx> = OreAlgebra(Pols)
Ind.<n> = PolynomialRing(QQ); Shift.<Sn> = OreAlgebra(Ind)

deq = guess([1,2,3,4,5,6],Diff)
deq.to_S(Shift)
```

returns a `TypeError: not an adequate algebra` because to_S expects rational coefficients.

**Comment by mkauers** [comment]
thanks. fixed.
