### ISSUE TITLE
Error 1 make error when building  ore_algebra

### ISSUE THREAD

**Issue by iajzenszmi** [mkauers/ore_algebra#30]
ian@ian-HP-Stream-Laptop-11-y0XX:~/ore_algebra$ ls
arb  build  COPYING  doc  Makefile  papers  README  README.md  setup.py  src
ian@ian-HP-Stream-Laptop-11-y0XX:~/ore_algebra$ make
sage -python setup.py build_ext --inplace
running build_ext
building 'ore_algebra.analytic.binary_splitting_arb' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python3/dist-packages/sage/cpython -I/usr/lib/python3/dist-packages/sage/libs/ntl -I/usr/lib/python3/dist-packages/sage/libs/flint -I/usr/lib/python3/dist-packages/sage/libs/arb -I/usr/lib/python3/dist-packages/cypari2 -I/usr/include -I/usr/lib/python3/dist-packages -I/usr/lib/python3/dist-packages/sage/ext -I/usr/include/python3.8 -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.8 -c src/ore_algebra/analytic/binary_splitting_arb.cpp -o build/temp.linux-x86_64-3.8/src/ore_algebra/analytic/binary_splitting_arb.o -std=c++11
src/ore_algebra/analytic/binary_splitting_arb.cpp:652:10: fatal error: mpfi.h: No such file or directory
  652 | #include "mpfi.h"
      |          ^~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
make: *** [Makefile:4: build] Error 1
ian@ian-HP-Stream-Laptop-11-y0XX:~/ore_algebra$ ^C
ian@ian-HP-Stream-Laptop-11-y0XX:~/ore_algebra$

**Comment by iajzenszmi** [comment]
On my Hp Stream 11 I am using Ubuntu 19 version operating system. I have installed Sage from operating system packages ie sudo apt install ...

**Comment by mezzarobba** [comment]
Try running `sudo apt build-dep sagemath` (as indicated in `README.md`), then `make` again.

**Comment by iajzenszmi** [comment]
I have run sudo apt build-dep sagemath and then run the make in
ore_algebra. There was an issue in that it could not find -larb. When
I ran make in arb-master there were compile errors.
 CC   ../build/arb_fmpz_poly/evaluate_arb.lo
    CC   ../build/arb_fmpz_poly/evaluate_arb_rectangular.lo
    CC   ../build/arb_fmpz_poly/evaluate_arb_horner.lo
    CC   ../build/arb_fmpz_poly/evaluate_acb_rectangular.lo
    CC   ../build/arb_fmpz_poly/../arb_fmpz_poly.lo
make[2]: Leaving directory '/home/ian/arb/arb-master/arb_fmpz_poly'
make[2]: Entering directory '/home/ian/arb/arb-master/arb_fpwrap'
    CC   ../build/arb_fpwrap/fpwrap.lo
fpwrap.c: In function ‘arb_fpwrap_double_1’:
fpwrap.c:201:16: error: ‘D_NAN’ undeclared (first use in this function)
  201 |         *res = D_NAN;
      |                ^~~~~
fpwrap.c:201:16: note: each undeclared identifier is reported only
once for each function it appears in
fpwrap.c: In function ‘arb_fpwrap_double_2’:
fpwrap.c:234:16: error: ‘D_NAN’ undeclared (first use in this function)
  234 |         *res = D_NAN;
      |                ^~~~~
fpwrap.c: In function ‘arb_fpwrap_double_3’:
fpwrap.c:270:16: error: ‘D_NAN’ undeclared (first use in this function)
  270 |         *res = D_NAN;
      |                ^~~~~
fpwrap.c: In function ‘arb_fpwrap_double_4’:
fpwrap.c:309:16: error: ‘D_NAN’ undeclared (first use in this function)
  309 |         *res = D_NAN;
      |                ^~~~~
fpwrap.c: In function ‘arb_fpwrap_cdouble_1’:
fpwrap.c:343:21: error: ‘D_NAN’ undeclared (first use in this function)
  343 |         res->real = D_NAN;
      |                     ^~~~~
fpwrap.c: In function ‘arb_fpwrap_cdouble_2’:
fpwrap.c:377:21: error: ‘D_NAN’ undeclared (first use in this function)
  377 |         res->real = D_NAN;
      |                     ^~~~~
fpwrap.c: In function ‘arb_fpwrap_cdouble_3’:
fpwrap.c:414:21: error: ‘D_NAN’ undeclared (first use in this function)
  414 |         res->real = D_NAN;
      |                     ^~~~~
fpwrap.c: In function ‘arb_fpwrap_cdouble_4’:
fpwrap.c:454:21: error: ‘D_NAN’ undeclared (first use in this function)
  454 |         res->real = D_NAN;
      |                     ^~~~~
fpwrap.c: In function ‘arb_fpwrap_double_1_int’:
fpwrap.c:489:16: error: ‘D_NAN’ undeclared (first use in this function)
  489 |         *res = D_NAN;
      |                ^~~~~
fpwrap.c: In function ‘arb_fpwrap_double_2_int’:
fpwrap.c:522:16: error: ‘D_NAN’ undeclared (first use in this function)
  522 |         *res = D_NAN;
      |                ^~~~~
fpwrap.c: In function ‘arb_fpwrap_double_3_int’:
fpwrap.c:558:16: error: ‘D_NAN’ undeclared (first use in this function)
  558 |         *res = D_NAN;
      |                ^~~~~
fpwrap.c: In function ‘arb_fpwrap_double_4_int’:
fpwrap.c:597:16: error: ‘D_NAN’ undeclared (first use in this function)
  597 |         *res = D_NAN;
      |                ^~~~~
fpwrap.c: In function ‘arb_fpwrap_cdouble_1_int’:
fpwrap.c:631:21: error: ‘D_NAN’ undeclared (first use in this function)
  631 |         res->real = D_NAN;
      |                     ^~~~~
fpwrap.c: In function ‘arb_fpwrap_cdouble_2_int’:
fpwrap.c:665:21: error: ‘D_NAN’ undeclared (first use in this function)
  665 |         res->real = D_NAN;
      |                     ^~~~~
fpwrap.c: In function ‘arb_fpwrap_cdouble_3_int’:
fpwrap.c:702:21: error: ‘D_NAN’ undeclared (first use in this function)
  702 |         res->real = D_NAN;
      |                     ^~~~~
fpwrap.c: In function ‘arb_fpwrap_cdouble_4_int’:
fpwrap.c:742:21: error: ‘D_NAN’ undeclared (first use in this function)
  742 |         res->real = D_NAN;
      |                     ^~~~~
fpwrap.c: In function ‘arb_fpwrap_cdouble_spherical_y’:
fpwrap.c:1175:21: error: ‘D_NAN’ undeclared (first use in this function)
 1175 |         res->real = D_NAN;
      |                     ^~~~~
fpwrap.c: In function ‘arb_fpwrap_double_hypgeom_pfq’:
fpwrap.c:1226:16: error: ‘D_NAN’ undeclared (first use in this function)
 1226 |         *res = D_NAN;
      |                ^~~~~
fpwrap.c: In function ‘arb_fpwrap_cdouble_hypgeom_pfq’:
fpwrap.c:1263:21: error: ‘D_NAN’ undeclared (first use in this function)
 1263 |         res->real = D_NAN;
      |                     ^~~~~
fpwrap.c: In function ‘arb_fpwrap_cdouble_zeta_zero’:
fpwrap.c:1372:21: error: ‘D_NAN’ undeclared (first use in this function)
 1372 |         res->real = D_NAN;
      |                     ^~~~~
fpwrap.c: In function ‘arb_fpwrap_double_legendre_root’:
fpwrap.c:1401:17: error: ‘D_NAN’ undeclared (first use in this function)
 1401 |         *res1 = D_NAN;
      |                 ^~~~~
fpwrap.c: In function ‘_arb_fpwrap_double_airy_zero’:
fpwrap.c:1430:16: error: ‘D_NAN’ undeclared (first use in this function)
 1430 |         *res = D_NAN;
      |                ^~~~~
fpwrap.c: In function ‘arb_fpwrap_double_lambertw’:
fpwrap.c:1476:16: error: ‘D_NAN’ undeclared (first use in this function)
 1476 |         *res = D_NAN;
      |                ^~~~~
fpwrap.c: In function ‘arb_fpwrap_cdouble_lambertw’:
fpwrap.c:1510:21: error: ‘D_NAN’ undeclared (first use in this function)
 1510 |         res->real = D_NAN;
      |                     ^~~~~
make[2]: *** [../Makefile.subdirs:60: ../build/arb_fpwrap/fpwrap.lo] Error 1
make[2]: Leaving directory '/home/ian/arb/arb-master/arb_fpwrap'
make[1]: *** [Makefile:128: libarb.so.2.12.0] Error 2
make[1]: Leaving directory '/home/ian/arb/arb-master'
make: *** [Makefile:148: library] Error 2
***@***.***:~/arb/arb-master$
================================================================
 8371 | static char
__pyx_doc_4sage_9structure_7element_2have_same_parent[] = "\n
Return ``True`` if and only if ``left`` and ``right`` have the\n
same parent.\n\n    .. WARNING::\n\n        This function assumes that
at least one of the arguments is a\n        Sage :class:`Element`.
When in doubt, use the slower\n        ``parent(left) is
parent(right)`` instead.\n\n    EXAMPLES::\n\n        sage: from
sage.structure.element import have_same_parent\n        sage:
have_same_parent(1, 3)\n        True\n        sage:
have_same_parent(1, 1/2)\n        False\n        sage:
have_same_parent(gap(1), gap(1/2))\n        True\n\n    These have
different types but the same parent::\n\n        sage: a = RLF(2)\n
    sage: b = exp(a)\n        sage: type(a)\n        <...
'sage.rings.real_lazy.LazyWrapper'>\n        sage: type(b)\n
<... 'sage.rings.real_lazy.LazyNamedUnop'>\n        sage:
have_same_parent(a, b)\n        True\n    ";
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/ore_algebra/analytic/binary_splitting_arb.cpp:8030:18: warning:
‘PyObject* __pyx_pw_4sage_9structure_7element_1parent(PyObject*,
PyObject*)’ defined but not used [-Wunused-function]
 8030 | static PyObject
*__pyx_pw_4sage_9structure_7element_1parent(PyObject *__pyx_self,
PyObject *__pyx_v_x) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/ore_algebra/analytic/binary_splitting_arb.cpp:8029:13: warning:
‘__pyx_doc_4sage_9structure_7element_parent’ defined but not used
[-Wunused-variable]
 8029 | static char __pyx_doc_4sage_9structure_7element_parent[] = "\n
   Return the parent of the element ``x``.\n\n    Usually, this means
the mathematical object of which ``x`` is an\n    element.\n\n
INPUT:\n\n    - ``x`` -- an element\n\n    OUTPUT:\n\n    - If ``x``
is a Sage :class:`Element`, return ``x.parent()``.\n\n    - Otherwise,
return ``type(x)``.\n\n    .. SEEALSO::\n\n        `Parents,
Conversion and Coercion
<http://doc.sagemath.org/html/en/tutorial/tour_coercion.html>`_\n
  Section in the Sage Tutorial\n\n    EXAMPLES::\n\n        sage: a =
42\n        sage: parent(a)\n        Integer Ring\n        sage: b =
42/1\n        sage: parent(b)\n        Rational Field\n        sage: c
= 42.0\n        sage: parent(c)\n        Real Field with 53 bits of
precision\n\n    Some more complicated examples::\n\n        sage: x =
Partition([3,2,1,1,1])\n        sage: parent(x)\n        Partitions\n
      sage: v = vector(RDF, [1,2,3])\n        sage: parent(v)\n
Vector space of dimension 3 over Real Double Field\n\n    The
following are not considered to be elements, so the type is\n
returned::\n\n        sage: d = int(42)  # Python int\n        sage:
parent(d)\n        <... 'int'>\n        sage: L = list(range(10))\n
    sage: parent(L)\n        <... 'list'>\n    ";
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions
-Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2
-Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
-D_FORTIFY_SOURCE=2
build/temp.linux-x86_64-3.8/src/ore_algebra/analytic/binary_splitting_arb.o
-lflint -lgmp -larb -o
build/lib.linux-x86_64-3.8/ore_algebra/analytic/binary_splitting_arb.cpython-38-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -larb
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-g++' failed with exit status 1
make: *** [Makefile:4: build] Error 1
***@***.***:~/ore_algebra$

**Comment by mezzarobba** [comment]
I don't understand the issue you encountered when trying to compile `arb` (`D_NAN` appears to be a macro defined in `flint/double_extras.h`, which I assume is included indirectly in `fpwrap.c` since I don't see it explicitly included but arb builds fine on my system). But you shouldn't need to build it yourself anyway, only to have the correct package (`libflint-arb-dev`, I believe) installed.

However, I also don't understand why the `g++` command line that you are quoting mentions `-larb`: on debian (and thus presumably on ubuntu), `arb` is called `flint-arb` to avoid a name clash with another package. Sage knows about that and, when building extension packages, it should automatically replace `arb` by `flint-arb` where needed.

Could it be that the `sage` command in your `$PATH` does not correpond to the system-wide Sage install, or that you set environment variables that influence gcc's behavior (e.g., `LIBRARY_PATH`)?
