### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by videlec** [mkauers/ore_algebra#4]
In order for doctest to pass (see  #3), each docstring should start with the directive
```
    sage: from ore_algebra import *
```
Currently running `sage -python setup.py test` we obtain
```
sage -t --long src/ore_algebra/guessing.py  # 18 doctests failed
sage -t --long src/ore_algebra/nullspace.py  # 80 doctests failed
sage -t --long src/ore_algebra/ideal.py  # 117 doctests failed
sage -t --long src/ore_algebra/ore_operator_1_1.py  # 335 doctests failed
sage -t --long src/ore_algebra/analytic/bounds.py  # 143 doctests failed
sage -t --long src/ore_algebra/analytic/function.py  # 73 doctests failed
sage -t --long src/ore_algebra/ore_algebra.py  # 132 doctests failed
sage -t --long src/ore_algebra/analytic/path.py  # 112 doctests failed
sage -t --long src/ore_algebra/analytic/polynomial_approximation.py  # 40 doctests failed
sage -t --long src/ore_algebra/analytic/__init__.py  # 51 doctests failed
sage -t --long src/ore_algebra/analytic/naive_sum.py  # 75 doctests failed
sage -t --long src/ore_algebra/analytic/shiftless.py  # 16 doctests failed
sage -t --long src/ore_algebra/generalized_series.py  # 100 doctests failed
sage -t --long src/ore_algebra/ore_operator.py  # 199 doctests failed
sage -t --long src/ore_algebra/analytic/examples/misc.py  # 2 doctests failed
sage -t --long src/ore_algebra/ore_operator_mult.py  # 43 doctests failed
sage -t --long src/ore_algebra/analytic/ui.py  # 12 doctests failed
sage -t --long src/ore_algebra/analytic/local_solutions.py  # 20 doctests failed
sage -t --long src/ore_algebra/tools.py  # 10 doctests failed
sage -t --long src/ore_algebra/analytic/examples/ssw.py  # 7 doctests failed
sage -t --long src/ore_algebra/analytic/binary_splitting.py  # 16 doctests failed
sage -t --long src/ore_algebra/analytic/examples/fcc.py  # 10 doctests failed
sage -t --long src/ore_algebra/analytic/analytic_continuation.py  # 3 doctests failed
sage -t --long src/dfinite_function.py  # 103 doctests failed
```

(once all tests pass, it would be easy to implement continuous integration using Travis CI)

**Comment by mezzarobba** [comment]
Hi Vincent,

I think the issue is actually with the testing command you implemented in setup.by, because running the tests manually with

src$ PYTHONPATH="." sage -t --long --warn-long 2 ore_algebra/

works for me.

(Perhaps related: I'm not sure if having moved setup.py to the root of the repository really makes things easier. I checked following our discussion, and pip does support installing from subdirectories of vcs repos.)

**Comment by videlec** [comment]
Hi Marc,

> I think the issue is actually with the testing command you implemented in setup.by
> because running the tests manually with
>
> src$ PYTHONPATH="." sage -t --long --warn-long 2 ore_algebra/

The option `--force-lib` makes it so that the file is not loaded before running the tests (without the option the doctester does a `%runfile` and then run the tests). Do you expect the users to load `ore_algebra` with `%runfile`/`%load`/`%attach` or with `import`?

My version makes it explicit that a copy/paste of the examples in the documentation will not work as is. Your version shows that the doctests pass *assuming the package is already loaded*.

> pip does support installing from subdirectories of vcs repos

If it does, feel free to put it back where it was! (but it should not be related at all to doctesting)

**Comment by mezzarobba** [comment]
On Monday, 23 April 2018 18:16:18 CEST Vincent Delecroix wrote:
> The option `--force-lib` makes it so that the file is not loaded
> before running the tests (without the option the doctester does a
> `%runfile` and then run the tests).

I thought it didn't make any difference when testing a whole package, 
but you're probably right.

In any case, the tests pass with --force-lib too, what I'm saying is 
that the failures you are seeing come from somewhere else...

> If it does, feel free to put it back where it was! (but it should not
> be related at all to doctesting)

..and I thought it may be a path issue, hence my side comment that it 
might be related to the move of setup.py (but I'm fine with it staying 
at the root, I don't care).

-- 
Marc
