### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by smelczer** [mkauers/ore_algebra#46]
Running numerical_transition_matrix throws a SyntaxError

```
File "/sagemath/9.1/local/lib/python3.7/site-packages/ore_algebra/analytic/path.py", line 431
    and (pol := self.value.polynomial()).is_term()
             ^
SyntaxError: invalid syntax
```

https://github.com/mkauers/ore_algebra/blob/4661dd06124b533beda4002f131050a49ac8f9c2/src/ore_algebra/analytic/path.py#L431

**Comment by mezzarobba** [comment]
Hi Steve,

Thanks for the bug report. Yes, this code is using a feature introduced 
in Python 3.8, which is the minimal version required by the upcoming 
Sage release, but apparently not by the previous ones.

-- 
Marc

**Comment by mezzarobba** [comment]
Fixed on master.

Steve, if you have a chance, would you mind running the test suite
(sage -t --long src/ore_algebra from the root of an ore_algebra 
checkout) to see if there are other similar issues?

Thanks,

-- 
Marc
