### ISSUE TITLE
Syntax error when importing Singularity_Analysis

### ISSUE THREAD

**Issue by smelczer** [mkauers/ore_algebra#54]
Running `from ore_algebra.analytic.singularity_analysis import bound_coefficients` on Sage 9.4 or Sage 9.6 gives 

```
File "<fstring>", line 1
    (n1=)
       ^
SyntaxError: invalid syntax
```

I'm not sure, but I think the issue comes from this line

https://github.com/mkauers/ore_algebra/blob/ab8cce958d047249dfeac784bc509baadebdf65b/src/ore_algebra/analytic/singularity_analysis.py#L1593

This issue was observed on mybinder.org instances through conda-forge (since Sage 9.7 fails to build through mybinder). Running Sage 9.7 on a local machine does not give this error.

**Comment by mezzarobba** [comment]
Hi Steve,
Thanks for the report. I have applied the fix you suggested, but I can't 
guarantee that there are no other issues with old versions of Python. 
(The issue is not with Sage 9.6 by itself but with the minimum Python 
version it requires.)
