### ISSUE TITLE
weird behaviour of guess

### ISSUE THREAD

**Issue by videlec** [mkauers/ore_algebra#56]
I have a nice list of coefficients : [my_coefficients.txt](https://github.com/mkauers/ore_algebra/files/10098087/my_coefficients.txt). Depending on how I truncate this list `guess` is answering either `1` or `(2*x^5 - 2*x)*Dx^3 + (15*x^4 - 3)*Dx^2 + 20*x^3*Dx`. More specifically, the following code
```
from ore_algebra import OreAlgebra, guess
R.<x> = QQ[]
Ax = OreAlgebra(R, 'Dx')
with open('my_coefficients.txt') as f:
    my_coeffs = [QQ(line) for line in f.readlines()]
for n in range(25, 43):
    try:
        op = guess(my_coeffs[:n], Ax)
    except ValueError:
        op = 'failed'
    print(n, op)
```
is printing
```
25 failed
26 failed
27 failed
28 (2*x^5 - 2*x)*Dx^3 + (15*x^4 - 3)*Dx^2 + 20*x^3*Dx
29 (2*x^5 - 2*x)*Dx^3 + (15*x^4 - 3)*Dx^2 + 20*x^3*Dx
30 1
31 (2*x^5 - 2*x)*Dx^3 + (15*x^4 - 3)*Dx^2 + 20*x^3*Dx
32 (2*x^5 - 2*x)*Dx^3 + (15*x^4 - 3)*Dx^2 + 20*x^3*Dx
33 (2*x^5 - 2*x)*Dx^3 + (15*x^4 - 3)*Dx^2 + 20*x^3*Dx
34 (2*x^5 - 2*x)*Dx^3 + (15*x^4 - 3)*Dx^2 + 20*x^3*Dx
35 (2*x^5 - 2*x)*Dx^3 + (15*x^4 - 3)*Dx^2 + 20*x^3*Dx
36 (2*x^5 - 2*x)*Dx^3 + (15*x^4 - 3)*Dx^2 + 20*x^3*Dx
37 (2*x^5 - 2*x)*Dx^3 + (15*x^4 - 3)*Dx^2 + 20*x^3*Dx
38 1
39 (2*x^5 - 2*x)*Dx^3 + (15*x^4 - 3)*Dx^2 + 20*x^3*Dx
40 (2*x^5 - 2*x)*Dx^3 + (15*x^4 - 3)*Dx^2 + 20*x^3*Dx
41 (2*x^5 - 2*x)*Dx^3 + (15*x^4 - 3)*Dx^2 + 20*x^3*Dx
42 1
```

**Comment by mkauers** [comment]
Thanks, I pushed a new version where this is fixed. The problem arises because you have many zeros in your data. The new version chooses a larger default value for the option 'ensure' in such cases. For recurrences and algebraic equations, the guesser removes such zeros, but for differential equations, that's not always the best thing to do. I think increasing 'ensure' is the better way to go.

**Comment by videlec** [comment]
Thanks! Indeed my series has only non-zero coefficients for n congruent to 1 mod 4.

**Comment by videlec** [comment]
I did not know about ["Why you should remove zeros from data before guessing"](https://dl.acm.org/doi/10.1145/3377006.3377017)... nice
