### ISSUE TITLE
Ore Algebra not working with Sage 8.7

### ISSUE THREAD

**Issue by maldun** [mkauers/ore_algebra#9]
Hi!

ore_algebra 0.3 does not work with sage 8.7.
The problem is (as it seems) a package wich is moved.

Replacing `from sage.rings.arith import xgcd` with
`from sage.arith.misc import xgcd` in guessing.py seems to solve the problem

**Comment by maldun** [comment]
Unfortunately a lot of the examples do not work anymore
Especially creating Ore Algebras:

> sage: A.<S> = OreAlgebra(K, ('S', lambda p: p(x+1), lambda p: K.zero()))
> 
> /home/sage/sage/local/lib/python2.7/site-packages/sage/structure/parent.pyx in sage.structure.parent.Parent.__call__ (build/cythonized/sage/structure/parent.c:8974)()
>     879         """
>     880         if self._element_constructor is None:
> --> 881             raise NotImplementedError(f"cannot construct elements of {self}")
>     882         cdef Py_ssize_t i
>     883         cdef R = parent(x)
> 
> NotImplementedError: cannot construct elements of Univariate Ore algebra in S over Fraction Field of Univariate Polynomial Ring in x over Rational Field

**Comment by mezzarobba** [comment]
Yes, ore_algebra 0.3 is a bit outdated by now; with recent sage 
versions, you have to use the git master branch. You can install it 
(after removing any older version installed with sage -i) using

sage -pip install --user git+https://github.com/mkauers/ore_algebra.git

-- 
Marc

**Comment by maldun** [comment]
Thanks for the fast answer!
It seem to work now. Thanks!
